In [1]:
import numpy as np

# Problem 1

In [2]:
np.eye(3, dtype="i") * 9

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]], dtype=int32)

# Problem 2

Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [3]:
arr = np.arange(2, 33, 2)
std = np.std(arr)
mean = np.mean(arr)
condition = (arr >= mean - std / 2) & (arr <= mean + std / 2)
arr[condition]

array([14, 16, 18, 20])

# Problem 3

Create a 9x9 array that contains only zeros of type int.

In [4]:
np.zeros((9, 9), dtype="i")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

# Problem 4

Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc...

In [5]:
try:
    n = int(input("Please enter the array size: "))
    if n > 9 or n < 1:
        raise ValueError()
except ValueError:
    print("You should input valid number in range [1, 9]")
    exit()

arr = np.ones((n, n), dtype="i")
arr *= np.arange(1, n + 1)
arr

Please enter the array size:  5


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]], dtype=int32)